/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_junniorsauceda;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.AEADBadTagException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author Junnior Sauceda
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        LlenarVentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tp_AgregarCar = new javax.swing.JTabbedPane();
        pn_AgregarCar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_marca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_Modelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_Precio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Sp_Año = new javax.swing.JSpinner();
        bt_AgregarCar = new javax.swing.JButton();
        tf_Color = new javax.swing.JTextField();
        pn_AgregarVen = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf_NomVend = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Sp_Vsell = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        tf_MoneyGen = new javax.swing.JTextField();
        bt_addVendedor = new javax.swing.JButton();
        pn_AgregClient = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tf_Nomclient = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Sp_CarrosCom = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        tf_Profesion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Sp_Edad = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        tf_Sueldo = new javax.swing.JTextField();
        bt_AgregarCliente = new javax.swing.JButton();
        pn_Vender = new javax.swing.JPanel();
        cb_vendedor = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cb_Cliente = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cb_Auto = new javax.swing.JComboBox<>();
        bt_Vender = new javax.swing.JButton();
        pn_Archivos = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_1 = new javax.swing.JTextArea();
        bt_abrirarchivo = new javax.swing.JButton();
        bt_guardarArchivo = new javax.swing.JButton();
        pn_Arboles = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_general = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_diario = new javax.swing.JTree();
        bt_CrearArchivoVentas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tp_AgregarCar.setBackground(new java.awt.Color(153, 255, 102));
        tp_AgregarCar.setForeground(new java.awt.Color(0, 0, 0));
        tp_AgregarCar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tp_AgregarCarStateChanged(evt);
            }
        });

        pn_AgregarCar.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Marca:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Modelo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Precio:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Año:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Color:");

        Sp_Año.setModel(new javax.swing.SpinnerNumberModel(2023, 1945, null, 1));

        bt_AgregarCar.setForeground(new java.awt.Color(0, 0, 0));
        bt_AgregarCar.setText("Agregar Vehiculo");
        bt_AgregarCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_AgregarCarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_AgregarCarLayout = new javax.swing.GroupLayout(pn_AgregarCar);
        pn_AgregarCar.setLayout(pn_AgregarCarLayout);
        pn_AgregarCarLayout.setHorizontalGroup(
            pn_AgregarCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AgregarCarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pn_AgregarCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(tf_Precio, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(tf_Modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(tf_marca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_AgregarCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(Sp_Año, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(tf_Color))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_AgregarCarLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(bt_AgregarCar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        pn_AgregarCarLayout.setVerticalGroup(
            pn_AgregarCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AgregarCarLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(pn_AgregarCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_AgregarCarLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_AgregarCarLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sp_Año, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pn_AgregarCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_AgregarCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_AgregarCar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        tp_AgregarCar.addTab("Agregar Vehiculo", pn_AgregarCar);

        pn_AgregarVen.setBackground(new java.awt.Color(51, 51, 51));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Vehiculos Vendidos:");

        Sp_Vsell.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Ganancias Generadas:");

        bt_addVendedor.setText("Agregar");
        bt_addVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addVendedorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_AgregarVenLayout = new javax.swing.GroupLayout(pn_AgregarVen);
        pn_AgregarVen.setLayout(pn_AgregarVenLayout);
        pn_AgregarVenLayout.setHorizontalGroup(
            pn_AgregarVenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AgregarVenLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pn_AgregarVenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(Sp_Vsell, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_AgregarVenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(tf_MoneyGen)
                        .addComponent(jLabel9)
                        .addComponent(tf_NomVend, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_AgregarVenLayout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addComponent(bt_addVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342))
        );
        pn_AgregarVenLayout.setVerticalGroup(
            pn_AgregarVenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AgregarVenLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_NomVend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sp_Vsell, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_MoneyGen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_addVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        tp_AgregarCar.addTab("Agregar Vendedor", pn_AgregarVen);

        pn_AgregClient.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Carros Comprados:");

        Sp_CarrosCom.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Profesion:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Edad:");

        Sp_Edad.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Sueldo Disponible:");

        bt_AgregarCliente.setText("Agregar");
        bt_AgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_AgregarClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_AgregClientLayout = new javax.swing.GroupLayout(pn_AgregClient);
        pn_AgregClient.setLayout(pn_AgregClientLayout);
        pn_AgregClientLayout.setHorizontalGroup(
            pn_AgregClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AgregClientLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(pn_AgregClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_AgregClientLayout.createSequentialGroup()
                        .addGroup(pn_AgregClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Profesion, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(429, 584, Short.MAX_VALUE))
                    .addGroup(pn_AgregClientLayout.createSequentialGroup()
                        .addGroup(pn_AgregClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_AgregClientLayout.createSequentialGroup()
                                .addGroup(pn_AgregClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(tf_Nomclient, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pn_AgregClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(Sp_CarrosCom, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pn_AgregClientLayout.createSequentialGroup()
                                .addGroup(pn_AgregClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(Sp_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pn_AgregClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))))
                        .addGap(107, 107, 107))))
            .addGroup(pn_AgregClientLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(bt_AgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_AgregClientLayout.setVerticalGroup(
            pn_AgregClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AgregClientLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pn_AgregClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_AgregClientLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_Nomclient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_AgregClientLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sp_CarrosCom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pn_AgregClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_AgregClientLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sp_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_AgregClientLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_Profesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_AgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        tp_AgregarCar.addTab("Agregar Cliente", pn_AgregClient);

        pn_Vender.setBackground(new java.awt.Color(51, 51, 51));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Vendedor:");

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Comprador:");

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Seleccione el Vehiculo:");

        bt_Vender.setText("Registrar Venta");
        bt_Vender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_VenderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_VenderLayout = new javax.swing.GroupLayout(pn_Vender);
        pn_Vender.setLayout(pn_VenderLayout);
        pn_VenderLayout.setHorizontalGroup(
            pn_VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_VenderLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pn_VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_VenderLayout.createSequentialGroup()
                        .addGroup(pn_VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(cb_Auto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_VenderLayout.createSequentialGroup()
                        .addGroup(pn_VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(cb_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addGroup(pn_VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(cb_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_VenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_Vender, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        pn_VenderLayout.setVerticalGroup(
            pn_VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_VenderLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pn_VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pn_VenderLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(cb_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                    .addGroup(pn_VenderLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(cb_vendedor)))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(cb_Auto, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(61, 61, 61)
                .addComponent(bt_Vender, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        tp_AgregarCar.addTab("Vender", pn_Vender);

        pn_Archivos.setBackground(new java.awt.Color(51, 51, 51));

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N

        ta_1.setColumns(20);
        ta_1.setRows(5);
        jScrollPane1.setViewportView(ta_1);

        bt_abrirarchivo.setText("Abrir Archivo");
        bt_abrirarchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_abrirarchivoMouseClicked(evt);
            }
        });

        bt_guardarArchivo.setText("Guardar Archivo");
        bt_guardarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarArchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_ArchivosLayout = new javax.swing.GroupLayout(pn_Archivos);
        pn_Archivos.setLayout(pn_ArchivosLayout);
        pn_ArchivosLayout.setHorizontalGroup(
            pn_ArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ArchivosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(pn_ArchivosLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(bt_abrirarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_guardarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        pn_ArchivosLayout.setVerticalGroup(
            pn_ArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ArchivosLayout.createSequentialGroup()
                .addGroup(pn_ArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_ArchivosLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_ArchivosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pn_ArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_abrirarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_guardarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tp_AgregarCar.addTab("Archivos", pn_Archivos);

        pn_Arboles.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Tienda");
        jt_general.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jt_general);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Ventas del Dia");
        jt_diario.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_diario);

        bt_CrearArchivoVentas.setText("Guardar acciones del dia");
        bt_CrearArchivoVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CrearArchivoVentasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_ArbolesLayout = new javax.swing.GroupLayout(pn_Arboles);
        pn_Arboles.setLayout(pn_ArbolesLayout);
        pn_ArbolesLayout.setHorizontalGroup(
            pn_ArbolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ArbolesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(bt_CrearArchivoVentas)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        pn_ArbolesLayout.setVerticalGroup(
            pn_ArbolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ArbolesLayout.createSequentialGroup()
                .addGroup(pn_ArbolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_ArbolesLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(pn_ArbolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_ArbolesLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(bt_CrearArchivoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tp_AgregarCar.addTab("Arboles", pn_Arboles);

        jPanel1.add(tp_AgregarCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 880, 530));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Venta Carros");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 550, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AgregarCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AgregarCarMouseClicked
        // TODO add your handling code here:
        FileWriter fw = null;
        BufferedWriter bw = null;
        File Archivocar = null;
        try {
            String marca = tf_marca.getText();
            String modelo = tf_Modelo.getText();
            int precio = Integer.parseInt(tf_Precio.getText());
            int año = Integer.parseInt(Sp_Año.getValue().toString());
            String Color = tf_Color.getText();
            Vehiculo x = new Vehiculo(marca, modelo, modelo, Color, año, precio);
            v.add(x);
            Archivocar = new File("./Carros.txt");
            fw = new FileWriter(Archivocar, true);
            bw = new BufferedWriter(fw);
            bw.write("[\n\t" + marca + ",\n\t" + modelo + ",\n\t" + Color + ",\n\t" + año + ",\n\t" + precio + ",\n];\n");
            bw.flush();
            tf_marca.setText("");
            tf_Modelo.setText("");
            tf_Precio.setText("");
            Sp_Año.setValue(2023);
            tf_Color.setText("");

            JOptionPane.showMessageDialog(this, "Agregado Exitosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();

        }
        try {
            bw.close();
            fw.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }

    }//GEN-LAST:event_bt_AgregarCarMouseClicked

    private void bt_addVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addVendedorMouseClicked
        // TODO add your handling code here:
        BufferedWriter bw = null;
        FileWriter fw = null;
        File ArchivoSellers = null;
        try {
            String nom = tf_NomVend.getText();
            int ventas = Integer.parseInt(Sp_Vsell.getValue().toString());
            double ganancias = Double.parseDouble(tf_MoneyGen.getText());
            Vendedor x = new Vendedor(nom, ventas, ganancias);
            Estafadores.add(x);
            ArchivoSellers = new File("./Vendedores.txt");
            fw = new FileWriter(ArchivoSellers, true);
            bw = new BufferedWriter(fw);
            bw.write("[\n\t" + nom + ",\n\t" + ventas + ",\n\t" + ganancias + ",\n];\n");
            bw.flush();

            JOptionPane.showMessageDialog(this, "Agregado Exitosamente");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
        tf_NomVend.setText("");
        Sp_Vsell.setValue(0);
        tf_MoneyGen.setText("");
        try {
            bw.close();
            fw.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_addVendedorMouseClicked

    private void bt_AgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AgregarClienteMouseClicked
        // TODO add your handling code here:
        BufferedWriter bw = null;
        FileWriter fw = null;
        File ArchivoClientes = null;
        try {
            String nom = tf_Nomclient.getText();
            int edad = Integer.parseInt(Sp_Edad.getValue().toString());
            String prof = tf_Profesion.getText();
            int compras = Integer.parseInt(Sp_CarrosCom.getValue().toString());
            double Sueldo = Double.parseDouble(tf_Sueldo.getText());
            Cliente x = new Cliente(nom, prof, edad, compras, Sueldo);
            Clientes.add(x);
            ArchivoClientes = new File("./Clientes.txt");
            fw = new FileWriter(ArchivoClientes, true);
            bw = new BufferedWriter(fw);
            bw.write("[\n\t" + nom + ",\n\t" + prof + ",\n\t" + edad + ",\n\t" + compras + ",\n\t" + Sueldo + ",\n];\n");
            bw.flush();
            JOptionPane.showMessageDialog(this, "Agregado Exitosamente");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
        tf_Nomclient.setText("");
        tf_Profesion.setText("");
        Sp_Edad.setValue(18);
        Sp_CarrosCom.setValue(0);
        tf_Sueldo.setText("");

        try {
            bw.close();
            fw.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_AgregarClienteMouseClicked

    private void tp_AgregarCarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tp_AgregarCarStateChanged
        // TODO add your handling code here:
        if (tp_AgregarCar.getSelectedIndex() == 3) {
            RellenarAutos();
            RellenarCompradores();
            RellenarVendedores();

        }
        if (tp_AgregarCar.getSelectedIndex() == 5) {
            RellenarAutos();
            RellenarCompradores();
            RellenarVendedores();
            int cont=0;
            DefaultTreeModel modeloArbolgen=new DefaultTreeModel(new DefaultMutableTreeNode("Admin"));
            DefaultMutableTreeNode Raizgen=(DefaultMutableTreeNode)modeloArbolgen.getRoot();
            Raizgen.add(new DefaultMutableTreeNode("Clientes"));
            DefaultMutableTreeNode son=((DefaultMutableTreeNode)Raizgen.getChildAt(0));
            for (Cliente cliente : Clientestemp) {
                son.add(new DefaultMutableTreeNode(cliente));
            }
            Raizgen.add(new DefaultMutableTreeNode("Vendedores"));
            DefaultMutableTreeNode son2=((DefaultMutableTreeNode)Raizgen.getChildAt(1));
            for (Vendedor vendedor : Estafadorestemp) {
                son2.add(new DefaultMutableTreeNode(vendedor));
            }
            Raizgen.add(new DefaultMutableTreeNode("Vehiculos"));
            DefaultMutableTreeNode son3=((DefaultMutableTreeNode)Raizgen.getChildAt(2));
            for (Vehiculo vehiculo : vtemp) {
                son3.add(new DefaultMutableTreeNode(vehiculo));
            }
            Raizgen.add(new DefaultMutableTreeNode("Ventas"));
            DefaultMutableTreeNode son4=((DefaultMutableTreeNode)Raizgen.getChildAt(3));
            for (Venta TotalVenta : TotalVentas) {
                son4.add(new DefaultMutableTreeNode(IDS.get(cont)));
                DefaultMutableTreeNode son5=((DefaultMutableTreeNode)son4.getChildAt(cont));
                son5.add(new DefaultMutableTreeNode(TotalVenta));
                cont++;
            }
            
            modeloArbolgen.reload();
            jt_general.setModel(modeloArbolgen);
            int cont2=0;
            DefaultTreeModel modeloArboldia=new DefaultTreeModel(new DefaultMutableTreeNode("Ventas del Dia"));
            DefaultMutableTreeNode Raizdia=(DefaultMutableTreeNode)modeloArboldia.getRoot();
            for (String id : ids) {
                Raizdia.add(new DefaultMutableTreeNode(id));
                DefaultMutableTreeNode child=(DefaultMutableTreeNode)Raizdia.getChildAt(cont2);
                child.add((new DefaultMutableTreeNode(Ventas.get(cont2))));
                cont2++;
            }
            modeloArboldia.reload();
            jt_diario.setModel(modeloArboldia);

        }
    }//GEN-LAST:event_tp_AgregarCarStateChanged
    public void genTreeGen(){
        RellenarAutos();
        RellenarCompradores();
        RellenarVendedores();
    }
    public void genTreeDia(){
        
    }
    private void bt_VenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_VenderMouseClicked
        // TODO add your handling code here:
        File f1 = null;
        File f2 = null;
        File f3 = null;
        BufferedWriter bw = null;
        FileWriter fw = null;
        try {
            f2 = new File("./Vendedores.txt");
            f3 = new File("./Clientes.txt");
            fw = new FileWriter(f3,false);
            bw= new BufferedWriter(fw);
            Clientestemp.get(cb_Cliente.getSelectedIndex()).setCarros
            ((Clientestemp.get(cb_Cliente.getSelectedIndex()).getCarros())+1);
            //bw.write("[\n\t" + nom + ",\n\t" + prof + ",\n\t" + edad + ",\n\t" + compras + ",\n\t" + Sueldo + ",\n];\n");
            for (Cliente cliente : Clientestemp) {
                bw.write("[\n\t" + cliente.getNombre() + ",\n\t" + cliente.getProfesion() + ",\n\t" + cliente.getEdad() + ",\n\t" + cliente.getCarros() + ",\n\t" + cliente.getSueldo() + ",\n];\n");
            }
            bw.flush();
            fw.close();
            bw.close();
            fw=new FileWriter(f2,false);
            bw=new BufferedWriter(fw);
            Estafadorestemp.get(cb_vendedor.getSelectedIndex()).setCantidad
            (Estafadorestemp.get(cb_vendedor.getSelectedIndex()).getCantidad()+1);
            Estafadorestemp.get(cb_vendedor.getSelectedIndex()).setMoney(Estafadorestemp.get
            (cb_vendedor.getSelectedIndex()).getMoney()+vtemp.get(cb_Auto.getSelectedIndex()).getPrecio());
            //bw.write("[\n\t" + nom + ",\n\t" + ventas + ",\n\t" + ganancias + ",\n];\n");
            for (Vendedor vendedor : Estafadorestemp) {
                bw.write("[\n\t" + vendedor.getNombre() + ",\n\t" + vendedor.getCantidad() + ",\n\t" + vendedor.getMoney() + ",\n];\n");
            }
            bw.flush();
            fw.close();
            bw.close();
            Venta v= new Venta();
            v.setVendedor(Estafadorestemp.get(cb_vendedor.getSelectedIndex()));
            v.setComprador(Clientestemp.get(cb_Cliente.getSelectedIndex()));
            v.setCarro(vtemp.get(cb_Auto.getSelectedIndex()));
            RellenarVentas(v);
            Ventas.add(v);
                    
            JOptionPane.showMessageDialog(this, "Venta realizada con Exito");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_VenderMouseClicked

    private void bt_abrirarchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_abrirarchivoMouseClicked
        // TODO add your handling code here:
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        ta_1.setText("");
        try {
            jfc = new JFileChooser("./");
            FileNameExtensionFilter filtro = 
                    new FileNameExtensionFilter(
                            "Archivos de Texto", "txt");
            jfc.setFileFilter(filtro);            
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION)
            {
               fichero = jfc.getSelectedFile();
               fr = new FileReader(fichero);
               br=new BufferedReader(fr);
               String linea;
               ta_1.setText("");
               while(  (linea=br.readLine()) !=null  ){
                   
                    ta_1.append(linea);
                    ta_1.append("\n");
                }
            } //fin if
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_abrirarchivoMouseClicked

    private void bt_guardarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarArchivoMouseClicked
        // TODO add your handling code here:
         
              
        FileWriter fw = null;
        BufferedWriter bw = null;
             try {
                 
                  File fichero=null;
                
                    fichero = jfc.getSelectedFile();
                                             
                fw = new FileWriter(fichero,false);
                bw = new BufferedWriter(fw);
                bw.write(ta_1.getText());
                ta_1.setText("");
                bw.flush();         
                JOptionPane.showMessageDialog(this, 
                        "Archivo guardado exitosamente");  
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                    bw.close();
                    fw.close();
                } catch (Exception e) {
           }
        
    }//GEN-LAST:event_bt_guardarArchivoMouseClicked

    private void bt_CrearArchivoVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CrearArchivoVentasMouseClicked
        // TODO add your handling code here:
        String nombre=JOptionPane.showInputDialog(this, "Ingrese el nombre del dia:");
        File f=null;
        FileWriter fw=null;
        BufferedWriter bw=null;
        int cont=0;
        try {
            f=new File("./"+nombre+".txt");
            fw= new FileWriter(f, true);
            bw= new BufferedWriter(fw);
            for (Venta Venta1 : Ventas) {
                bw.write("[\n\t"+ids.get(cont)+",\n\t"+Venta1.getComprador().getNombre()+
                        ",\n\t"+Venta1.getVendedor().getNombre()+",\n\t"+Venta1.getCarro());
                cont++;
            }
            bw.flush();
            JOptionPane.showMessageDialog(this, "Archivo guardado");
            ids=new ArrayList<>();
            Ventas=new ArrayList<>();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            fw.close();
            bw.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_CrearArchivoVentasMouseClicked
    public void ReescribirClientes() {
        File f = null;
        BufferedWriter bw=null;
        FileWriter fw=null;
        try {
            f= new File("./Clientes");
            fw= new FileWriter(f);
            bw=new BufferedWriter(fw);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }

    public String Id() {
        String id = "";
        for (int i = 0; i < 4; i++) {
            id += ran.nextInt(9);
        }
        for (int i = 0; i < 4; i++) {
            int a = ran.nextInt(abc.length());
            if (a >= 0) {
                id += abc.charAt(a);
            } else {
                id += abc.charAt((a + 1));
            }
        }
        return id;

    }
    public void LlenarVentas(){
        File F=null;
        FileReader fr = null;
        BufferedReader br = null;
        try {
            F=new File("./VentasTotales.txt");
            fr=new FileReader(F);
            br= new BufferedReader(fr);
            String linea;
            while((linea=br.readLine())!=null){
                String Id=br.readLine();
                Id=Id.trim();
                Id=Id.substring(0, Id.length()-1);
                String Comprador=br.readLine();
                Comprador=Comprador.trim();
                Comprador=Comprador.substring(0, Comprador.length()-1);
                String Vendedor=br.readLine();
                Vendedor=Vendedor.trim();
                Vendedor=Vendedor.substring(0, Vendedor.length()-2);
                Cliente x=new  Cliente();
                x.setNombre(Comprador);
                Vendedor ven= new Vendedor();
                ven.setNombre(Vendedor);
                Venta sell= new Venta();
                sell.setComprador(x);
                sell.setVendedor(ven);
                TotalVentas.add(sell);
                IDS.add(Id);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error(Puede que uno de los archivos este vacio)");
            e.printStackTrace();
        }
        try {
            fr.close();
            br.close();
        } catch (Exception e) {
        }
                
    }
    public void RellenarVentas(Venta V){
        File F=null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            F=new File("./VentasTotales.txt");
            fw=new FileWriter(F, true);
            bw= new BufferedWriter(fw);
            String Id=Id();
            ids.add(Id);
            bw.write("[\n\t"+Id+",\n\t"+V.getComprador().getNombre()+",\n\t"+V.getVendedor().getNombre()+"];\n");
            bw.flush();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error(Puede que uno de los archivos este vacio)");
            e.printStackTrace();
        }
        try {
            fw.close();
            bw.close();
        } catch (Exception e) {
        }
                
    }
    public void RellenarAutos() {
        File f1 = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        FileReader fr = null;
        BufferedReader br = null;
        try {
//            bw.write("[\n\t" + marca + ",\n\t" + modelo + ",\n\t" + Color + ",\n\t" + año + ",\n\t" + precio + ",\n];\n");

            f1 = new File("./Carros.txt");

            if (f1.exists()) {
                DefaultComboBoxModel modelo = new DefaultComboBoxModel();
                fr = new FileReader(f1);
                br = new BufferedReader(fr);
                String linea;
                while (((linea = br.readLine()) != null)) {
                    String marca = br.readLine();
                    if (marca != null) {
                        marca = marca.trim();
                        marca = marca.substring(0, marca.length() - 1);

                        String model = br.readLine();
                        model = model.trim();
                        model = model.substring(0, model.length() - 1);

                        String Color = br.readLine();
                        Color = Color.trim();
                        Color = Color.substring(0, Color.length() - 1);

                        String temp = br.readLine();
                        temp = temp.trim();
                        temp = temp.substring(0, temp.length() - 1);
                        String ano = br.readLine();
                        ano = ano.trim();
                        ano = ano.substring(0, ano.length() - 1);

                        int año = Integer.parseInt(ano);

                        String precio = br.readLine();
                        precio = precio.trim();
                        precio = precio.substring(0, precio.length() - 1);

                        double Price = Double.parseDouble(precio);

                        Vehiculo ve = new Vehiculo(marca, model, ano, temp, año, Price);
                        vtemp.add(ve);
                        modelo.addElement(ve);
                    }
                }
                cb_Auto.setModel(modelo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error(Puede que uno de los archivos este vacio)");
            e.printStackTrace();
        }
        try {

            fr.close();
            br.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }

    public void RellenarVendedores() {

        File f2 = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        FileReader fr = null;
        BufferedReader br = null;
        f2 = new File("./Vendedores.txt");

        //bw.write("[\n\t" + nom + ",\n\t" + ventas + ",\n\t" + ganancias + ",\n];\n");
        if (f2.exists()) {

            try {
                DefaultComboBoxModel modelo = new DefaultComboBoxModel();
                fr = new FileReader(f2);
                br = new BufferedReader(fr);
                String linea;
                while ((linea = br.readLine()) != null) {
                    String nombre = br.readLine();
                    nombre = nombre.trim();
                    nombre = nombre.substring(0, nombre.length() - 1);

                    String Ventas = br.readLine();
                    Ventas = Ventas.trim();
                    Ventas = Ventas.substring(0, Ventas.length() - 1);

                    int cant = Integer.parseInt(Ventas);
                    String money = br.readLine();
                    money = money.trim();
                    money = money.substring(0, money.length() - 1);

                    double ganacias = Double.parseDouble(money);
                    String temp = br.readLine();
                    Vendedor Vend = new Vendedor(nombre, cant, ganacias);
                    modelo.addElement(Vend);
                    Estafadorestemp.add(Vend);
                }
                cb_vendedor.setModel(modelo);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error");
                e.printStackTrace();
            }
            try {

                fr.close();
                br.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error");
                e.printStackTrace();
            }
        }
    }

    public void RellenarCompradores() {
        File f3 = null;
        FileReader fr = null;
        BufferedReader br = null;
        try {

            f3 = new File("./Clientes.txt");
            if (f3.exists()) {
//bw.write("[\n\t" + nom + ",\n\t" + prof + ",\n\t" + edad + ",\n\t" + compras + ",\n\t" + Sueldo + ",\n];\n");

                try {
                    DefaultComboBoxModel modelo = new DefaultComboBoxModel();
                    fr = new FileReader(f3);
                    br = new BufferedReader(fr);
                    String linea;
                    while ((linea = br.readLine()) != null) {
                        String nombre = br.readLine();
                        if (nombre != null) {
                            nombre = nombre.trim();
                            nombre = nombre.substring(0, nombre.length() - 1);

                            String temp = br.readLine();
                            temp = temp.trim();
                            temp = temp.substring(0, temp.length() - 1);

                            String Age = br.readLine();
                            Age = Age.trim();
                            Age = Age.substring(0, Age.length() - 1);

                            int edad = Integer.parseInt(Age);
                            String Profe = br.readLine();
                            Profe = Profe.trim();
                            Profe = Profe.substring(0, Profe.length() - 1);

                            String Cantcar = br.readLine();
                            Cantcar = Cantcar.trim();
                            Cantcar = Cantcar.substring(0, Cantcar.length() - 1);

                            int comprados = Integer.parseInt(Profe);
                            String Sueldodisp = br.readLine();
                            Sueldodisp = Sueldodisp.trim();
                            Sueldodisp = Sueldodisp.substring(0, Sueldodisp.length() - 1);

                            double Disp = Double.parseDouble(Cantcar);
                            Cliente c = new Cliente(nombre, temp, edad, comprados, Disp);
                            modelo.addElement(c);
                            Clientestemp.add(c);
                        }
                    }
                    cb_Cliente.setModel(modelo);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error");
                    e.printStackTrace();
                }

            }
        } catch (Exception e) {
        }
        //            bw.write("[\n\t" + nom + ",\n\t" + prof + ",\n\t" + edad + ",\n\t" + compras + ",\n\t" + Sueldo + ",\n];\n");
        try {
            fr.close();
            br.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    JFileChooser jfc=new JFileChooser();
    Random ran = new Random();
    ArrayList<Vehiculo> v = new ArrayList<>();
    ArrayList<Vendedor> Estafadores = new ArrayList<>();
    ArrayList<Cliente> Clientes = new ArrayList<>();
    ArrayList<Vehiculo> vtemp = new ArrayList<>();
    ArrayList<Vendedor> Estafadorestemp = new ArrayList<>();
    ArrayList<Cliente> Clientestemp = new ArrayList<>();
    ArrayList<Venta> Ventas = new ArrayList<>();
    ArrayList<Venta> TotalVentas = new ArrayList<>();
    ArrayList<String> IDS = new ArrayList<>();
    ArrayList<String> ids = new ArrayList<>();
    String abc = "abcdefghijklmnopqrstuvwxyz";


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Sp_Año;
    private javax.swing.JSpinner Sp_CarrosCom;
    private javax.swing.JSpinner Sp_Edad;
    private javax.swing.JSpinner Sp_Vsell;
    private javax.swing.JButton bt_AgregarCar;
    private javax.swing.JButton bt_AgregarCliente;
    private javax.swing.JButton bt_CrearArchivoVentas;
    private javax.swing.JButton bt_Vender;
    private javax.swing.JButton bt_abrirarchivo;
    private javax.swing.JButton bt_addVendedor;
    private javax.swing.JButton bt_guardarArchivo;
    private javax.swing.JComboBox<String> cb_Auto;
    private javax.swing.JComboBox<String> cb_Cliente;
    private javax.swing.JComboBox<String> cb_vendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jt_diario;
    private javax.swing.JTree jt_general;
    private javax.swing.JPanel pn_AgregClient;
    private javax.swing.JPanel pn_AgregarCar;
    private javax.swing.JPanel pn_AgregarVen;
    private javax.swing.JPanel pn_Arboles;
    private javax.swing.JPanel pn_Archivos;
    private javax.swing.JPanel pn_Vender;
    private javax.swing.JTextArea ta_1;
    private javax.swing.JTextField tf_Color;
    private javax.swing.JTextField tf_Modelo;
    private javax.swing.JTextField tf_MoneyGen;
    private javax.swing.JTextField tf_NomVend;
    private javax.swing.JTextField tf_Nomclient;
    private javax.swing.JTextField tf_Precio;
    private javax.swing.JTextField tf_Profesion;
    private javax.swing.JTextField tf_Sueldo;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTabbedPane tp_AgregarCar;
    // End of variables declaration//GEN-END:variables
}
